### ISSUE TITLE
Missing Files "icons" and "prefabs" in Thunderstore release

### ISSUE THREAD

**Issue by venoMantis** [Debonairesnake6/LoLItems#1]
The release version on Thunderstore does not function on its own, outputting the error messages "Failed to read data for the AssetBundle '...\BepInEx\plugins\Debo-LoLItems\items'." and "Failed to read data for the AssetBundle '...\BepInEx\plugins\Debo-LoLItems\prefabs'." while not putting any of the items into the game. Downloading the named "items" and "prefabs" files from LolItem's Assets folder on here and putting the files in the mod's folder fixed the mod and the items are added to the game. Either those files are missing from the Thunderstore zip or a pointer to where the data is actually stored in the release version is set incorrectly somewhere.

**Comment by Debonairesnake6** [comment]
Whoops! I'll look into getting this fixed shortly.

**Comment by Debonairesnake6** [comment]
This should be fixed in version 0.1.1. I have also updated my build steps to hopefully make sure this issue doesn't occur again in the future.
