### ISSUE TITLE
1.9 huntress

### ISSUE THREAD

**Issue by VelvetBanshee** [Debonairesnake6/LoLItems#17]
Very cool mod! i noticed on a run yesterday while playing huntress that my attacks weren't proccing on hit triggers like bands, harvester scythe, etc. 

I went to test today if i was really not just seeing things and it appears im not getting any on hit triggers to work other than BoRK.
then i tested without the mod and it seemed to work fine.
i use the flurry primary if that could have something to do with it. (i didn't test the main primary)

**Comment by VelvetBanshee** [comment]
Mul-t primary seems to also not proc things, sounds like a proc coef. issue

**Comment by Debonairesnake6** [comment]
I think I found the issue. Will do quick test and then push the update if it works.

**Comment by Debonairesnake6** [comment]
It make take a little bit for the thunderstore to recognize the new version is out, but once you can download the update you should be good to go. Thanks for reporting this issue!
