### ISSUE TITLE
Heartsteel proc sound WAY too loud

### ISSUE THREAD

**Issue by knightmare013** [Debonairesnake6/LoLItems#19]
already found a problem with the hearsteel change with the sound being way too loud that really needs to be addressed as soo as possible

**Comment by Debonairesnake6** [comment]
Really? Did you adjust some of the in game sound settings? I'm using the defaults iirc and it isn't much louder than anything else like plasma shrimp.

**Comment by knightmare013** [comment]
i do have my sounds very very low (SFX 10%, Master 21&) and it's still very loud

side node, the damage proc seems a bit too much, could tone it down a bit from 50% max HP

**Comment by knightmare013** [comment]
maybe could be a huntress thing possibly?

**Comment by Debonairesnake6** [comment]
I'm not sure. I'll do some testing and hope to have it fixed over the weekend if I can replicate it. I normally do my testing with commando. I'm not sure why the character played would matter, but bugs can be quite strange sometimes lol.

What would you suggest the damage gets reduced to? I think it significantly falls of late game but know it can be strong early.

**Comment by knightmare013** [comment]
might just be my imagination with it's damage tbh

**Comment by Debonairesnake6** [comment]
Thinking about this again, it's probably because I just play the sound, rather than specifying it's a sound effect so it isn't getting reduced by your settings. It was honestly quite difficult to try and implement the sound effect since the guides for it just kept giving me errors.

Im not sure if this would be a 5 minute fix, or take me a few days like the initial implementation did.

**Comment by Debonairesnake6** [comment]
I fixed it on my local copy, when I push the new version (I'll do it when I merge the linked branch) it'll scale with your SFX volume slider and no longer kill your ears. I'll do some more testing with damage from the item to see if I need to scale it back.

**Comment by Debonairesnake6** [comment]
I'm going to push the new version now. I don't think I'm going to change the damage. Here is my rationale, you can reopen the ticket if you disagree and still want to discuss:

- The damage is on a single target with a 10 second cool down, compared to other on-hit or proc chance items which can proc multiple times in a row late game and can be aoe (sticky bomb, uke)
- It can be hard to control exactly what gets damaged, so it can be hard to use it on the target you want
- The damage scales with how much health you can gain, as the base health generally doesn't give a huge amount of damage. You don't often get reds early, so you'll generally have a short window to stack hp and get a really beefy hit in

If anything I think the health could be scaled down (which would also nerf damage), but leaving it for now.
