### ISSUE TITLE
Heartsteel sound still too loud

### ISSUE THREAD

**Issue by Xeinset** [Debonairesnake6/LoLItems#21]
![изображение_2023-09-13_183018173](https://github.com/Debonairesnake6/LoLItems/assets/78896807/86ff0603-706f-4ac9-a299-c1c5c67a7beb)
It's still too loud even with this fix. For me it's unplayable to hear this peaking sounds every 10 second

**Comment by Debonairesnake6** [comment]
I've reduced the base sound of the item. Please reopen the ticket if you think it's still too loud.
