### ISSUE TITLE
idea for new item: kraken slayer-Green item

### ISSUE THREAD

**Issue by knightmare013** [Debonairesnake6/LoLItems#23]
I think having Kraken slayer in the game would be pretty cool

Could have the effect of: Every 3rd hit deals bonus damage for X% base/TOTAL damage (+X% Per stack).

**Comment by knightmare013** [comment]
Though it might be pretty good as a powerful Red item

**Comment by Debonairesnake6** [comment]
Thanks for the suggestion! How would you recommend balancing it? I had a similar concept with Bork (although it's been reworked since) where I had to have a cooldown since it got xrazy quite quickly.

**Comment by knightmare013** [comment]
Eell since Bork does current enemy health, it scales on enemy states rather than survivor stats, which would make it go out of hand fast.

Since the kraken would scale on the survivors base/TOTAL damage, it would be easier to balance.

I'd say you could make it a green item of it would deal base damage, or a red item if it deals TOTAL damage.

**Comment by knightmare013** [comment]
hey, was wondering how you think of the idea?

**Comment by Debonairesnake6** [comment]
I like it and look to implement it. Aiming to have it our before next Friday.

**Comment by Debonairesnake6** [comment]
The item has been added. Let me know what you think of the balance and I can fine tune it if need be in future patches. I think it's fairly balanced based on the napkin math I normal use to balance items though.
