### ISSUE TITLE
Models for the mod

### ISSUE THREAD

**Issue by knightmare013** [Debonairesnake6/LoLItems#25]
Hello, I'm not sure exactly where to write this since I'm still very new to GitHub, but I wanted to offer some help with making models for the items in your mod.

The models I could make would be very basic with the textures, but I could make them very accurate to the items in the game they're from based on their icons.

If you have any questions, do write me back soon, I'd be quite excited to help out with your mod.

**Comment by Debonairesnake6** [comment]
That would be awesome, thank you! You can try to follow https://docs.github.com/en/get-started/quickstart/contributing-to-projects to create your own branch and add the files. Then I can work on that same branch and import them into the game, or I could also show you how to do it yourself.

**Comment by Debonairesnake6** [comment]
@knightmare013 I'm going to close this thread for now as I'm assuming you've moved onto other things. If you are still interested in helping out we can re-open this and I can give you anything you need to get started.
