### ISSUE TITLE
Guardian's Blade Duplication

### ISSUE THREAD

**Issue by Debonairesnake6** [Debonairesnake6/LoLItems#30]
Source: https://discord.com/channels/562704639141740588/567832879879553037/1162566196609155142

![image](https://github.com/Debonairesnake6/LoLItems/assets/22126580/5c0c0544-c6dd-4aca-adb5-2a347ad44565)

**Comment by knightmare013** [comment]
there is another bug with the item and engineer, when i have a guardian's blade engi's turrets won't attack enemies

**Comment by Debonairesnake6** [comment]
I already found that issue on fixed it on my local copy. Once I figure out the duplication issue I'll push the fix for both.
