### ISSUE TITLE
Guinsoo's Rageblade Balance

### ISSUE THREAD

**Issue by shawncrobinson** [Debonairesnake6/LoLItems#32]
My friends and I love a lot of the item ideas in this mod but guinsoo's being so overtuned is singlehandedly forcing us to not use the mod, given the lack of a config to disable selected items. I've managed to crash the host twice.

Increasing the proc coefficient of a player by 0.1 flat is a pretty insane white item. With high item counts it has the tendency to exacerbate performance issues in the late game with crazy proc chains exponentially increasing the number of projectiles on screen, like the incredibly rare 57-leaf clover but much more easily accessible. Even with low item counts, the item's strength rivals that of crit glasses.

The easiest solution would probably be to change this item's tier from a white to a green. There are a few green items that if stacked to 10+ easily break the game, so this item wouldn't be out of place among the better half of green items. 

Alternatively, you could lower the proc coefficient increase. Something like +0.1 for the first guinsoos, then +0.025 for each one after feels like a good enough increase that I'd still be excited to find a guinsoos or guinsoos printer.

**Comment by Debonairesnake6** [comment]
I've been meaning to implement some configuration files, and this gave me an interesting idea. How would you like it if i made everything configurable? This could include:

- Disable items
- Values of effects
- Rarity
- Anything else?

**Comment by shawncrobinson** [comment]
Configuration like that would be amazing and greatly appreciated. Just those three alone would be better a better baseline set of configs than what I've seen from most item mods in ror2.
 
If you're up for it you could allow for changing corrupted items to regular items. This would increase compatability with other mods that might also want to corrupt the base game's items. Some initial thoughts on implementing this feature:
- Corrupted should probably be an option in the rarity configuration.
- You could make this generalizable to any item by allowing the user provide a list of items that will be converted to the corrupt item.
- Instead of making this generalizable, you could just restrict the corrupted option to just items that are by default corrupted, like Blade of the Ruined King.
  - This would let you avoid needing to generalize this to all items.
  - Items that are corrupted by default could have a pre-defined list of base items that they convert. You could still choose to allow changing it via config, or not. Up to you.

Now that you've mentioned it, I'm surprised I haven't seen any config for changing item rarities. Combine rarity changes with value changes and you get a lot of flexibility for users self-balancing the mod, or even just changing stuff around for fun. Imagine Kraken Slayer as a red with +200% base damage every 3rd hit.
