### ISSUE TITLE
Project Halted?

### ISSUE THREAD

**Issue by AndrinoC** [Debonairesnake6/LoLItems#40]
It's been a while since the last update.
I really love this project and am eager to see more content and bugfixes!

**Comment by Debonairesnake6** [comment]
Hey @AndrinoC, I'm glad you've enjoyed the mod! I haven't spent as much time on Ror2 recently and as a result the content has slowed down. We still have some things that should come shortly, but I would expect it to be slow until the DLC arrives.

**Comment by AndrinoC** [comment]
@Debonairesnake6 I believe that this makes perfect sense, thanks for the quick answer!
