### ISSUE TITLE
The game wont open

### ISSUE THREAD

**Issue by anartoast** [Debonairesnake6/LoLItems#41]
Hey it's me again, took a time off the game for techinical reasons, the pc would bsod when trying to play the game lol.
Anyway, after installing the mod the game gets stuck at 100%, i tried both with and without. I'll send the log. 
It says something about the Twitch character. When i removed it, the game opened just fine.
[LogOutput.log](https://github.com/user-attachments/files/16101700/LogOutput.log)

**Comment by Debonairesnake6** [comment]
Hey @anartoast, good to hear from you again!

Looking at your log messages, I'm not sure how my mod is causing the problem. The following is the stack trace of the final error which would have crashed your game:

`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Twitch.Twitch.PopulateFromBody (System.String bodyName) (at <8fe05f7f9bca484a879517eaa5efe0fe>:IL_0095)
Twitch.Twitch.ItemDisplaySetup () (at <8fe05f7f9bca484a879517eaa5efe0fe>:IL_0000)
RoR2.RoR2Application+<InitializeGameRoutine>d__69.MoveNext () (at <78ca0507428e4dbea7a28fe14402f720>:IL_0282)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <85d1d3e7744a4a47b5f51883bf40bba2>:IL_0026)`

Can you please send me your full mod list? I'd need to try enabling and disabling other mods (mainly the Twitch one) to see if that would also resolve the crash.

**Comment by anartoast** [comment]
Here: 0190804f-d66f-f163-74e5-6c019fc4c5d0
It may be an issue with a random mod cause the same thing happened with another mod i've tried. I unistalled the Twitch mod and the game worked fine.

**Comment by Debonairesnake6** [comment]
Thanks, I'll look at it over the weekend.

**Comment by anartoast** [comment]
Also i've talked to some people and ALL survivors mod after the devotion update makes so everytime you close your game it crashes instead (??), So that may be affecting it too?

**Comment by Debonairesnake6** [comment]
I haven't been able to produce a crash yet which includes my mod in the stack trace. If your crashes also don't indicate my mod is the issue then I'll end up closing this ticket as I'm not sure what I can do.

**Comment by anartoast** [comment]
It has to do with the Twitch character mod by XiaoXiao921 i just downloaded it again and it still stops working at 100% load. I don't know if it's something to do with the mod Risk of Waiting because it changes the way of how loading works, but something is up when i use the LoLitems and Twitch character mod together.
Probably can just be resolved my not using the two together tbh, it lookslike a thing you'd have too much work with.
I copied the files just now, the games is stuck at 100%, if it helps:

[LogOutput.log](https://github.com/user-attachments/files/16181641/LogOutput.log)

**Comment by Debonairesnake6** [comment]
I'm going to close this issue for now. If you can generate an error from my mod I'll re-open it and see what I can do, but I can't do much if it's due to another mod.
