### ISSUE TITLE
Bug with Shrine of Blood and Void Cradle

### ISSUE THREAD

**Issue by Squeemos** [Debonairesnake6/LoLItems#8]
Updated today to 0.1.5 and found an issue where you can't hit the void cradles or the shrine of bloods.

**Comment by Debonairesnake6** [comment]
Can you please provide more info. What other mods are you using? What of my items did you pick up when you noticed this?

My mod doesn't interact with Void cradles or shrines of blood so I can't think of why it would be causing it rn.

**Comment by Squeemos** [comment]
Okay so I went to do some testing because I wasn't sure if there was an item problem with something, or something entirely.

Just did a clean run with Acrid where I didn't grab anything and tried to hit a Shrine of Blood, and still wasn't able to. However, when I disable LolItems I'm able to hit it just fine. Is there a good way to give a list of mods?

The thing that's the most interesting for me is that prior to 0.1.5 it worked with no problems.

**Comment by Debonairesnake6** [comment]
You can export your profile as a file using the mod launcher and upload it here so I can import it and try for myself. I'll be able to do some testing myself tonight to see if I can replicate it with my setup and push and fix if I get it solved.

**Comment by Squeemos** [comment]
Here's the code for current list of mods:
0187bfe8-8426-4b32-080b-6efc35f2aead

**Comment by Debonairesnake6** [comment]
Found the issue and fixed it. Will release the update shortly for it. Thanks for reporting it!
